INSERT INTO method (method_code, method_name, method_type) VALUES
(554, 'INSTRUMENTAL - Gas Filter Correlation Thermo Electron 48i-TLE', 'FRM'),
(54, 'INSTRUMENTAL - NONDISPERSIVE INFRARED', 'FRM'),
(593, 'INSTRUMENTAL - Gas Filter Correlation Teledyne API 300 EU / T300U', 'FRM'),
(93, 'INSTRUMENTAL - GAS FILTER CORRELATION CO ANALYZER', 'FRM'),
(588, 'INSTRUMENTAL - Gas Filter Correlation Ecotech EC9830T', 'FRM'),
(158, 'INSTRUMENTAL - NONDISPERSIVE INFRARED PHOTOMETRY', 'FRM'),
(174, 'Instrumental - Nondispersive Infrered Photometry', 'FRM'),
(130, 'LGR (Los GAtos Research - Off-Axis ICOS Cavity Ringdown Spectroscopy', 'Non-FRM'),
(106, 'INSTRUMENTAL - NONDISPERSIVE INFRARED PHOTOMETRY', 'FRM'),
(55, 'INSTRUMENTAL - Gas Filter Correlation Thermo Electron 48C-TL', 'Non-FRM'),
(51, 'INSTRUMENTAL - NONDISPERSIVE INFRARED', 'FRM'),
(200, 'Teledyne-API Model 200EUP or T200UP - Photolytic-Chemiluminescence', 'FEM'),
(574, 'Instrumental - Chemiluminescence Thermo Electron 42C-TL, 42i-TL', 'FRM'),
(90, 'INSTRUMENTAL - GAS-PHASE CHEMILUMINESCENCE', 'FRM'),
(99, 'INSTRUMENTAL - GAS PHASE CHEMILUMINESCENCE', 'FRM'),
(157, 'Instrumental - Chemiluminescence', 'FRM'),
(35, 'INSTRUMENTAL - CHEMILUMINESCENCE', 'FRM'),
(74, 'INSTRUMENTAL - CHEMILUMINESCENCE', 'FRM'),
(599, 'Instrumental - Chemiluminescence Teledyne API 200 EU/501', 'FRM'),
(212, 'Teledyne Model T500U - Cavity Attenuated Phase Shift Spectroscopy', 'FEM'),
(42, 'INSTRUMENTAL - CHEMILUMINESCENCE', 'FRM'),
(186, 'Instrumental - Chemiluminescence', 'FRM'),
(590, 'Instrumental - Chemiluminescence Ecotech EC9841T', 'FRM'),
(560, 'INSTRUMENTAL - Pulsed Fluorescent 43C-TLE/43i-TLE', 'FEM'),
(60, 'INSTRUMENTAL - PULSED FLUORESCENT', 'FEM'),
(592, 'Instrumental - Ultraviolet Fluorescence EC9850T', 'FEM'),
(100, 'INSTRUMENTAL - ULTRAVIOLET FLUORESCENCE', 'FEM'),
(9, 'INSTRUMENTAL - PULSED FLUORESCENT', 'FEM'),
(600, 'Instrumental - Ultraviolet Fluorescence API 100 EU', 'FEM'),
(77, 'INSTRUMENTAL - FLUORESCENCE DETECTION', 'FEM'),
(61, 'INSTRUMENTAL - ULTRA VIOLET FLUORESCENCE', 'FEM'),
(92, 'AUTOMATED ANALYZER - ULTRAVIOLET FLUORESCENCE', 'FEM'),
(39, 'INSTRUMENTAL - ULTRA VIOLET STIMULATED FLUORESCNC', 'FEM'),
(47, 'INSTRUMENTAL - ULTRA VIOLET', 'FEM'),
(87, 'INSTRUMENTAL - ULTRA VIOLET ABSORPTION', 'FEM'),
(19, 'INSTRUMENTAL - ULTRA VIOLET', 'FEM'),
(199, 'Instrumental - Chemiluminescence API Model 265E and T265', 'FEM'),
(190, 'Instrumental - UV absorption photometry/UV 2B model 202 and 205', 'FEM'),
(91, 'INSTRUMENTAL - ULTRAVIOLET RADIATION ABSORBTN', 'FEM'),
(901, 'Instrumental - Ultra Violet 2B Model 202', 'Non-FRM'),
(56, 'INSTRUMENTAL - ULTRA VIOLET', 'FEM'),
(187, 'Instrumental - Ecotech Serinus 10', 'FEM'),
(53, 'INSTRUMENTAL - ULTRA VIOLET', 'FEM'),
(160, 'INSTRUMENTAL - ULTRAVIOLET ABSORPTION', 'FEM'),
(112, 'INSTRUMENTAL - ULTRAVIOLET ABSORPTION', 'FEM');
